src/lisp.go

let式のループに対応した

---

src/lisp.go

Cons append pair

---

src/lisp.go

数学関数の追加(sqrt, sin, cos, tan,atan,rand)

---

src/lisp.go

and演算子、or演算子のバグを暫定措置として改修した

---

src/lisp.go

(define (hoge) (define a 10))
みたいなのを

ENV(環境スコープ)のネスト化 前準備

---

README.md
src/lisp.go

データ構造の定義
evalの修正
buildの修正
functionの修正

ENV(環境スコープ)のネスト化

---

src/lisp.go
src/lisp_test.go

エラーメッセージの整理

---

src/lisp.go
src/lisp_test.go

遅延評価(delay,force)の実装完了

---

src/lisp.go
src/lisp_test.go

文字型のサポート及びバグ改修

---

README.md
src/.gitignore
src/lisp.go
src/lisp_test.go

パフォーマンスバグの改修

---

src/lisp.go
src/lisp_test.go

https://github.com/hidekuno/go-scheme/issues/52

変数評価における引数チェックのバグ

---

docker-compose.yml
docker/Dockerfile
docker/envs

下記の条件であれば、windows,macでも動作する。
- dockerをインストール(docker-compose)
- X11サーバをインストール(ex. cygwin,xquartz)

Dockerに対応した

---

src/draw/draw_gtk.go

Image処理のexposeイベントに考慮していなかった

---

src/draw/draw_gtk.go
src/draw_main.go
src/scheme/draw/lisp_draw.go
src/scheme/web/lisp_web.go

パッケージ宣言を見やすくした

---

src/draw/common.go
src/draw/gtk.go
src/draw/qt.go
src/draw_qt_main.go

昔作ったQtの練習プログラムを追加

---

src/scheme/lisp.go
src/scheme/lisp_test.go

rust-elisp実装中に発生したバグ対応

---

src/scheme/lisp.go
src/scheme/lisp_test.go

https://github.com/hidekuno/go-scheme/issues/104
https://github.com/hidekuno/go-scheme/issues/103
https://github.com/hidekuno/go-scheme/issues/101
https://github.com/hidekuno/go-scheme/issues/99

bug fix. (issue #104,103,101,99)

---

src/scheme/lisp.go
src/scheme/lisp_test.go

https://github.com/hidekuno/go-scheme/issues/100

reduce関数をSRFI仕様に合わせた

---

src/scheme/lisp.go
src/scheme/lisp_test.go

https://github.com/hidekuno/go-scheme/issues/108

forceバグのfix

---

src/draw/gtk.go
src/scheme/draw/lisp_draw.go
src/scheme/lisp.go
src/scheme/lisp_test.go
src/web/websocket.go
src/web_wasm_main.go

_(アンダースコア)の変数名を修正した

---

docker-compose.yml
docker/Dockerfile

Dockerfileにビルドを追加した

---

src/scheme/lisp.go

LetLoop構造体の廃止

---

src/scheme/lisp.go
src/scheme/lisp_test.go

https://github.com/hidekuno/go-scheme/issues/119

https://github.com/hidekuno/go-scheme/issues/119

---

src/scheme/lisp.go
src/scheme/lisp_test.go

quotient関数のふるまいを標準にした

---

src/scheme/lisp.go
src/scheme/lisp_test.go

cond関数にて複数の式を評価するように対応

---

src/scheme/lisp.go
src/scheme/lisp_test.go

load-file関数のエラーチェックを強化した

---

src/scheme/lisp.go
src/scheme/lisp_test.go

シンボルについて日本語に対応した

---

src/scheme/lisp.go

大幅なパフォーマンス向上がみられたので反映する

---

src/scheme/draw/lisp_draw_test.go
src/scheme/lisp_test.go

テストコード見直しの追加

---

examples/common.scm
examples/sierpinski.scm
examples/tree.scm
src/scheme/lisp.go
src/scheme/lisp_test.go

begin関数の追加

---

src/scheme/lisp.go

begin関数のコードを見直した

---

src/scheme/lisp.go
src/scheme/lisp_test.go

expt関数について実数の計算を対応した

---

src/scheme/lisp.go
src/scheme/lisp_test.go

display,newline関数を追加

---

Dockerfile

Dockerについてschemeプログラム移行に対応した

---

study/.gitignore

検証用プログラムのgitignoreを修正

---

Dockerfile

Dockerfileを改良した

---

samples/frame.scm
src/draw/gtk.go
src/scheme/draw/lisp_draw.go
src/scheme/draw/lisp_draw_test.go

gtkバージョン取得APIの追加(サンプルプログラムの削除)

gtkバージョン取得APIの追加(サンプルプログラムの削除)

---

src/lisp_wasm.go
src/wasm/wasm_exec.js

Support Go 1.13 for web assembly

Support Go 1.13 for web assembly

---

Dockerfile
src/scheme/lisp.go
src/scheme/lisp_test.go

string-append,get-environement-variable関数を追加

string-append,get-environement-variable関数を追加

---

src/.gitignore
src/wasm/go.js
src/wasm/websocket.js
src/web/websocket.go

wasmのUIを少し修正

---

src/scheme/draw/lisp_draw_test.go

gtkバージョン取得関数のテストコードを改善

---

draw/common.go
draw/gtk.go

DrawDemoプログラムの改修

---

scheme/lisp.go
scheme/lisp_test.go

複数式をサポートした(issue-114)

---

scheme/lisp.go
scheme/lisp_test.go

文字列エラーのコード、メッセージを変更した(issue-115)

文字列エラーのコード、メッセージを変更した(issue-115)

---

scheme/list.go
scheme/list_test.go

iota関数のバグを改修(issue-155)

---

scheme/number.go
scheme/operation.go

実数計算処理の見直し（issue-185 ）

---

scheme/syntax.go
scheme/syntax_test.go

apply関数のサポート

---

scheme/lisp.go
scheme/list.go
scheme/list_test.go
scheme/syntax.go

map,filter関数を組み込み関数に対応

---

scheme/lisp.go
scheme/syntax.go

beginを関数化した

---

scheme/lisp.go
scheme/list.go
scheme/list_test.go

for-each関数を組み込み関数に対応させた

---

scheme/lisp_test.go

テストコードを改良した(より安全に)

---

scheme/char.go
scheme/lisp.go
scheme/list.go
scheme/number.go
scheme/string.go

 ;interface Atomの廃止

---

scheme/list.go

listの表記処理の不具合を解消

---

scheme/math.go
scheme/math_test.go

math関連の関数を追加

---

scheme/util.go
scheme/util_test.go

数の性質及びデータ型の種類を判定する関数を追加

---

scheme/list.go
scheme/list_test.go

SICPプログラムが動作しないの不具合を対応する

---

scheme/list_test.go

テストコードを追加した

---

scheme/util.go
scheme/util_test.go

https://github.com/hidekuno/go-scheme/issues/219

型チェック関数に、いくつかの関数を追加

---

scheme/operation.go
scheme/operation_test.go

ビット演算にいくつかの関数を追加

---

scheme/string.go
scheme/string_test.go

string-joinとstring-splitを追加した

---

scheme/char.go
scheme/char_test.go

文字(キャラクタ)処理にいくつか関数を追加

---

scheme/io.go
scheme/io_test.go
scheme/lisp.go
scheme/lisp_test.go
scheme/syntax.go
scheme/syntax_test.go

 テストコードを追加

---

scheme/char.go
scheme/io.go
scheme/io_test.go
scheme/lisp.go
scheme/lisp_test.go
scheme/list.go
scheme/list_test.go
scheme/number.go
scheme/string.go
scheme/syntax_test.go

read,read-charのテストコードを追加した

---

scheme/char.go

char型についてdisplay関数の表示不具合を改修

---

scheme/io.go

read-charの実装を見直し

---

scheme/syntax.go
scheme/syntax_test.go

letで引数なしで実行してもチェックをかけるようにした

---

scheme/operation.go
scheme/operation_test.go
scheme/util.go
scheme/util_test.go

twos_exponentとnative-endian関数を追加

twos_exponentとnative-endian関数を追加

---

scheme/string.go
scheme/string_test.go

string,string-scan,string-scan-right関数を追加

string,string-scan,string-scan-right関数を追加

---

scheme/char.go
scheme/char_test.go

digit->integer,integer->digitを追加

digit->integer,integer->digitを追加

---

scheme/list.go
scheme/list_test.go
scheme/number.go

append!, delete!,set-car!,set-cdr!関数を追加

append!, delete!,set-car!,set-cdr!関数を追加

---

scheme/lisp.go
scheme/syntax.go
scheme/syntax_test.go

機能限定の継続をサポートした

---

scheme/char.go
scheme/lisp.go
scheme/number.go
scheme/string.go
scheme/string_test.go

number->string, string->numberの改修

number->string, string->numberの改修

---

scheme/lisp.go
scheme/lisp_test.go
scheme/list.go
scheme/list_test.go
scheme/number.go

ソート関数(sort,stable-sort,merge)を追加

ソート関数(sort,stable-sort,merge)を追加

---

scheme/draw/lisp_draw.go
scheme/draw/lisp_draw_test.go

draw-lineの仕様をrust-elispに合わせた

---

scheme/util.go

go vetの結果に対応した

---

scheme/number.go

有理数について独自の実装からmath/big/Ratに書き換えた

有理数について独自の実装からmath/big/Ratに書き換えた

---

scheme/boolean.go
scheme/boolean_test.go
scheme/lisp.go
scheme/syntax.go
scheme/syntax_test.go

boolean関数の追加

---

scheme/lisp.go
scheme/list.go
scheme/list_test.go
scheme/number.go
scheme/string.go
scheme/string_test.go
scheme/util.go
scheme/util_test.go

vector関数の追加

---

scheme/string.go
scheme/string_test.go

string系の関数を追加した。

---

draw/gtk.go

スクリーンサイズを変更した
